[package]
name = "faupi"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1.7.0", features = ["http1", "server"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml = "0.9.34"
thiserror = "2.0.16"
